#! /usr/bin/env python
# encoding: utf-8

'''
@author: Milos Subotic <milos.subotic.sm@gmail.com>
@license: MIT

'''

###############################################################################

import os
import sys

###############################################################################

def prerequisites(ctx):
	if sys.platform.startswith('linux'):
		# Ubuntu.
		ctx.exec_command2('sudo apt-get -y install libsfml-dev')
	elif sys.platform == 'msys':
		# MSYS2 Windows.
		ctx.exec_command2('pacman --noconfirm -S mingw-w64-i686-sfml')

def options(opt):
	pass

def configure(conf):
	conf.env.append_value('CXXFLAGS', '-std=c++11')
	conf.env.append_value('LIB', 'pthread')
	
	conf.check_cfg(
		package = 'sfml-graphics',
		uselib_store = 'SFML',
		args = '--cflags --libs',
		mandatory = True
	)
	
	
def build(bld):
	bld.stlib(
		source = bld.path.ant_glob('src/*.cpp'),
		includes = 'include',
		export_includes = 'include',
		use = 'SFML pthread',
		target = 'emulator'
	)

###############################################################################
